name: Code Checker

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    name: Lint Code
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 custom_components/

      - name: Check flake8 configuration
        run: |
          echo "Flake8 configuration:"
          cat .flake8
